IGFoodProject/Models/Territory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IGFoodProject.Models
{
    public class Territory
    {

        public int TerritoryId { get; set; }

        public int? AreaId { get; set; }

        public string TerritoryName { get; set; }

        public string CreateBy { get; set; }

        public DateTime? CreateDate { get; set; }
        public string AreaName { get; set; }
    }
}

IGFoodProject/Controllers/TerritoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IGFoodProject.DAL;
using IGFoodProject.Models;
using IGFoodProject.Utility;

namespace IGFoodProject.Controllers
{
    public class TerritoryController : Controller
    {
        private TerritoryDAL TerriDal=new TerritoryDAL() ;
        // GET: Territory
        public ActionResult Index(int id=0)
        {
            UtilityDAL dal= new UtilityDAL();
            List<Area> areaList = dal.GetArea();
            Territory aTerritory= new Territory();
             aTerritory = TerriDal.GetTerritory(id);
            var tuple = new Tuple<IEnumerable<Area>, Territory>(areaList, aTerritory);
            return View(tuple);
        }

        public ActionResult SaveTerritory(Territory entity)
        {
            ResultResponse aResponse = new ResultResponse();
            entity.CreateBy = Session[SessionCollection.LoginUserEmpId].ToString();
            entity.CreateDate = DateTime.Now;
            aResponse = TerriDal.SaveTerritory(entity);
            return Json(aResponse, JsonRequestBehavior.AllowGet);

        }

        public ActionResult TerritoryList()
        {
           List<Territory> territoryList= new List<Territory>();
            territoryList = TerriDal.GetAllTerritory();
            return View(territoryList);
        }
    }
}

IGFoodProject/Views/Territory/Index.cshtml
@model Tuple<IEnumerable<IGFoodProject.Models.Area>, IGFoodProject.Models.Territory>


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-3">
                                <h3 class="card-title">
                                    <span class="fa fa-list"></span> Territory Entry
                                </h3>
                            </div>
                            <div class="col-md-4">
                                <a onclick="@("window.location.href='" + @Url.Action("TerritoryList", "Territory") + "'");">
                                    <h3 class="card-title">
                                        <span class="fa fa-list"></span> Territory List
                                    </h3>
                                </a>
                            </div>
                        </div>
                    </div>


                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card-body">
                                <div class="form-group" id="divArea">
                                    <label for="ddlArea">Area</label>
                                    <select class="form-control select2" id="ddlArea" style="width: 100%;">
                                        <option value="">-------Select Area------</option>
                                        @foreach (var item in Model.Item1)
                                        {

                                            <option value="@item.AreaId">@item.AreaName </option>
                                        }
                                    </select>
                                </div>

                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card-body">
                                <div class="form-group" id="divTerritory">
                                    <label for="territoryId ">Territory Name</label>
                                    <input type="text" class="form-control" id="territoryId" value="@Model.Item2.TerritoryName" />
                                </div>
                            </div>
                        </div>

                    </div>
                    <div>

                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button class="pull pull-right btn btn-primary" onclick="SaveFinal()">Submit</button>
                        </div>
                    </div>

                </div>

            </div>

        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>

@section Scripts{
    <script>
        $(function() {
            $('#ddlArea').val(@Model.Item2.AreaId).trigger('change');
        });

        function SaveValidation() {
            var isValid = true;
            if ($('#ddlArea').val() == null || $('#ddlArea').val() == '') {
                ValidationColorChangeNew('ddlArea', 'divArea', 'Area Required', true);
                isValid = false;
            }

            if ($('#territoryId').val() == null || $('#territoryId').val() == '') {
                ValidationColorChangeNew('territoryId', 'divTerritory', 'Enter TerritoryName', true);
                isValid = false;
            }
            if (isValid == false) {
                ShowMessage("Some Values Required");
            }
            return isValid;
        }

        function SaveFinal() {
            if (SaveValidation()) {
                swal({
                    title: "Are you sure?",
                    text: "",
                    type: "success",
                    showCancelButton: true,
                    cancelButtonClass: 'btn-secondary waves-effect',
                    confirmButtonClass: 'btn-success waves-effect waves-light',
                    confirmButtonText: 'Yes!',
                    closeOnConfirm: false

                }, function() {
                    $('.confirm').prop("disabled", true);
                    $('.cancel').prop("disabled", true);
                    SaveTerritory();

                });
            }

        }

        function SaveTerritory() {
            var jsonData = {};
            jsonData["TerritoryId"] = @Model.Item2.TerritoryId;
            jsonData["AreaId"] = $("#ddlArea").val();
            jsonData["TerritoryName"] = $("#territoryId").val();


            var urlpath = '@Url.Action("SaveTerritory", "Territory")';

            $.ajax({
                contentType: "application/json",
                data: JSON.stringify(jsonData),
                dataType: 'json',
                url: urlpath,
                type: "POST"
            })
                .success(function(result) {

                    if (result.pk > 0) {

                        swal("SucessFull");
                        window.location.href = '@Url.Action("TerritoryList", "Territory")';
                    } else {
                        swal("Duplecate Terrytory Name!!!!!");
                        window.location.href = '@Url.Action("TerritoryList", "Territory")';
                    }
                });
        }

    </script>
}

IGFoodProject/Views/Territory/TerritoryList.cshtml
@model IEnumerable<IGFoodProject.Models.Territory>

@{
    ViewData["Title"] = "RequisitionList";
}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-3">
                                <h3 class="card-title"><span class="fa fa-list"></span> Territory List </h3>
                            </div>
                            <div class="col-md-4">
                                <a onclick="location.href = '@Url.Action("Index", "Territory")'"><h3 class="card-title"><span class="fa fa-plus"></span> New Territory Entry</h3></a>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->

                    <div class="card-body">
                        <table class="table dataTable table-bordered table-striped table-hover">
                            <thead>
                            <tr style="background-color: aliceblue">
                                <th style="text-align: center">SL</th>
                                <th style="text-align: center">AreaName</th>
                                <th style="text-align: center">TerritoryName</th>
                                <th style="text-align: center">CreateBy</th>
                                <th style="text-align: center">CreateDate</th>
                                <th style="text-align: center">Action</th>
                            </tr>
                            </thead>
                            <tbody class="Traylist">
                                @{
                                    int i = 1;
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td style='text-align: center'>
                                                @i
                                            </td>
                                            <td style='text-align: center'>@item.AreaName</td>
                                            <td style='text-align: center'>@item.TerritoryName</td>
                                            <td style='text-align: center'>@item.</td>
                                            <td style='text-align: center'>@Convert.ToDateTime(item.CreateDate).ToString("dd MMM yyyy")  </td>

                                            <td style="text-align: center">

                                                <button type="button" class="btn btn-sm btn-info" data-toggle="modal" data-target="#myModal" onclick="location.href = '@Url.Action("Index", "Territory", new { @id = item.TerritoryId })'">Edit</button>
                                               

                                            </td>
                                            

                                        </tr>
                                        ++i;
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>

        </div>





        <!-- /.row -->
    </div><!-- /.container-fluid -->
   
</section>
@section scripts{
    <script>
        function LoadLiveBirdDressedById(id) {
            var urlpath = '@Url.Action("TerritoryList", "Territory")';
            $.ajax({
                url: urlpath,
                type: "Get",
                dataType: 'html',
                async: false,
                data: { id: id },
                success: function (data) {
                    $('#LiveBirdDressPartial').empty();

                    $('#LiveBirdDressPartial').html(data);
                }
            });


        }
        function BirdDressEntry() {
            window.location.href = '@Url.Action("Index", "Territory")';
        }
    </script>
}