IGFoodProject/Controllers/ProductPackSizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IGFoodProject.Utility;
using IGFoodProject.DAL;
using IGFoodProject.Models;

namespace IGFoodProject.Controllers
{
    public class ProductPackSizeController : Controller
    {
        // GET: ProductPackSize
        public ActionResult ProductPackSizeList()
        {
            ProductPackSizeDAL aDal = new ProductPackSizeDAL();
            List<tbl_ProductPackSize> alist = aDal.GetPackSizeList();
            return View(alist);
        }
        public ActionResult AddPackSize(int id = 0)
        {
            ViewBag.packsizeid = id;
            return View();
        }
        public JsonResult CheckPackSize(string group)
        {

            ProductPackSizeDAL aDAL = new ProductPackSizeDAL();

            int desig = aDAL.CheckPackSize(group);

            return Json(desig , JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult SavePackSize(tbl_ProductPackSize aGroup)
        {
            ResultResponse aResponse = new ResultResponse();
            ProductPackSizeDAL aDAL = new ProductPackSizeDAL();

            string entryBy = Session[SessionCollection.UserName].ToString();
            aGroup.CreateBy = entryBy;
            aGroup.UpdateBy = entryBy;
            aResponse.isSuccess = aDAL.SavePackSize(aGroup);

            return Json(aResponse, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetPackSizeByID(int id)
        {
            ProductPackSizeDAL aDal = new ProductPackSizeDAL();
            return Json(aDal.GetPackSizeForEdit(id),JsonRequestBehavior.AllowGet);

        }
        public JsonResult DeletePackSize(int id)
        {
            ResultResponse aResponse = new ResultResponse();
            ProductPackSizeDAL aDAL = new ProductPackSizeDAL();


            aResponse.isSuccess = aDAL.DeletePacksize(id);

            return Json(aResponse, JsonRequestBehavior.AllowGet);
        }
    }
}

IGFoodProject/Views/ProductPackSize/AddPackSize.cshtml

@{
    ViewData["Title"] = "AddPackSize";
}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Product Pack Size Entry</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-primary" onclick="@("window.location.href='" + @Url.Action("ProductPackSizeList", "ProductPackSize") + "'");" class="btn btn-info btn-rounded waves-effect waves-light pull-right">
                                <i class="fa fa-arrow-left"></i>
                                Back To Product Pack Size List
                            </button>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div>
                        <div class="card-body">
                            <div class="form-group" id="divPackSize">
                                <label for="txtPackSize">Pack Size</label>
                                <input type="text" class="form-control" id="txtPackSize" placeholder="Enter Pack Size">
                            </div>
                            <div class="form-group" id="divPackWeight">
                                <label for="txtPackSize">Pack Weight</label>
                                <input type="text" class="form-control" id="txtPackWeight" placeholder="Enter Pack Weight">
                            </div>

                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="chkActive" checked="checked">
                                <label class="form-check-label" for="chkActive">Is Active</label>
                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button class="btn btn-primary" onclick="SaveFinal()">Submit</button>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
                <!-- Form Element sizes -->
                <!-- /.card -->
                <!-- /.card -->
                <!-- Input addon -->
                <!-- /.card -->
                <!-- Horizontal Form -->
                <!-- /.card -->

            </div>
            <!--/.col (left) -->
            <!-- right column -->
            <div class="col-md-6">

            </div>
            <!--/.col (right) -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
    <input id="txtPackSizeId" type="number" style="display:none;" value="@ViewBag.packsizeid">
</section>

@section Scripts{
    <script>
        $(function () {

            var id = $('#txtPackSizeId').val();

            if (id > 0) {
                OdEdit(id);
            }
        });


        function SaveFinal() {

            //Swal("Hello World");
            if (Validation() == true) {

                swal({
                    title: "Are you sure?",
                    text: "",
                    type: "success",
                    showCancelButton: true,
                    cancelButtonClass: 'btn-secondary waves-effect',
                    confirmButtonClass: 'btn-success waves-effect waves-light',
                    confirmButtonText: 'Yes!',
                    closeOnConfirm: false

                }, function () {
                    $('.confirm').prop("disabled", true);
                    $('.cancel').prop("disabled", true);
                    SavePackSize();

                });
            }

        }

        function ValidatePackSize(group) {

            var result = 0;
            var urlpath = '@Url.Action("CheckPackSize", "ProductPackSize")';
            $.ajax({
                url: urlpath,
                dataType: 'json',
                type: "Get",
                data: { group: group },
                async: false,
                success: function (data) {

                    result = data;
                }
            });
            return result;
        }

        function Validation() {

            var rVal = true;
            var message;
            if (($('#txtPackSize').val() == "") || ($('#txtPackSize').val() == null)) {
                ValidationColorChange('txtPackSize', 'divPackSize', false);
                rVal = false;
                message = "Some Values Required";

            }

            var ddata = ValidatePackSize($('#txtPackSize').val());
            var groupid = $('#txtPackSizeId').val();

            if (ddata > 0 && groupid == 0) {
                rVal = false;
                message = "Duplicate Product Pack Size Please Change!!!";

            }


            if (rVal == false) {
                ShowMessage(message);
            }

            return rVal;
        }

        function SavePackSize() {
            var jsonData = {};


            jsonData["PackSizeId"] = parseInt($('#txtPackSizeId').val());

            jsonData["PackSizeName"] = $('#txtPackSize').val();
            jsonData["PackWeight"] = $('#txtPackWeight').val();

            jsonData["IsActive"] = $('#chkActive').is(':checked');


            var urlpath = '@Url.Action("SavePackSize", "ProductPackSize")';

            $.ajax({

                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsonData),
                dataType: 'json',
                url: urlpath,
                type: "POST"
            })
                .success(function (result) {

                    if (result.isSuccess) {

                        //$('.confirm').prop("disabled", false);
                        //$('.cancel').prop("disabled", false);
                        ////swal.close();

                        swal("Product Pack Size Saved Successfull");
                        window.location.href = '@Url.Action("ProductPackSizeList", "ProductPackSize")';


                    }
                });


        }


        function OdEdit(id) {
           
            var url = '@Url.Action("GetPackSizeByID", "ProductPackSize")';
            $.ajax({
                url: url,
                dataType: 'json',
                data: { id: id },
                type: "Get",
                async: false,
                success: function (data) {

                    $('#txtPackSizeId').val(id);
                   
                    var test = data.PackSizeName;
                    $('#txtPackSize').val(data.PackSizeName);
                    if (data.isActive == true)
                        $('#chkActive').prop('checked', true);

                    else
                        $('#chkActive').prop('checked', false);


                }
            });

        }
    </script>
}



IGFoodProject/Views/ProductPackSize/ProductPackSizeList.cshtml
@model IEnumerable<IGFoodProject.Models.tbl_ProductPackSize>

@{
    ViewData["Title"] = "ProductPackSizeList";
}



@{
    int count = 0;
}

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div>
                    <button type="button" onclick="@("window.location.href='" + @Url.Action("AddPackSize", "ProductPackSize") + "'");" class="btn btn-info btn-rounded waves-effect waves-light pull-right">
                        <span class="btn-label">
                            <i class="fa fa-arrow-left"></i>
                        </span>
                        Back To Pack Size Entry

                    </button>
                </div>

                <div class="card-header">
                    <h3 class="card-title">Product Pack Size List</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example2" class="table dataTable table-bordered table-hover">
                        <thead>
                            <tr>
                                <th style="text-align:center">#</th>
                                <th style="text-align:center">PackSizeName</th>
                                <th style="text-align:center">Create Date</th>
                                <th style="text-align:center">Create By</th>
                                <th style="text-align:center">Update Date</th>
                                <th style="text-align:center">Update By</th>
                                <th style="text-align:center">Is Active</th>
                                <th style="text-align:center"></th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                count++;
                                <tr>
                                    <td style="text-align:center">@count</td>
                                    <td style="text-align:center">@item.PackSizeName</td>
                                    <td style="text-align:center">@Convert.ToDateTime(item.CreateDate).ToString("dd-MMM-yyyy")</td>
                                    <td style="text-align:center">@item.CreateBy</td>
                                    @if (item.UpdateDate != null)
                                    {
                                        <td style="text-align:center">@Convert.ToDateTime(item.UpdateDate).ToString("dd-MMM-yyyy")</td>
                                    }
                                    else
                                    {
                                        <td style="text-align:center"></td>
                                    }

                                    <td style="text-align:center">@item.UpdateBy</td>
                                    <td style="text-align:center">@item.IsActive</td>
                                    <td>
                                        @Html.ActionLink("Edit", "AddPackSize", "ProductPackSize", new { id = item.PackSizeId }, new { @class = "btn btn-primary btn-xs btn-custom btn-rounded waves-effect waves-light" })
                                        <button class="btn btn-danger  btn-xs btn-custom btn-rounded waves-effect waves-light" onclick="PackSizeDelete(@item.PackSizeId)"> Delete</button>
                                    </td>
                                </tr>

                            }


                        </tbody>

                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
@*</div>*@
@*<script src="~/plugins/jquery/jquery.min.js"></script>*@
@section Scripts{
    <script>
            $(function () {

                
            });
    </script>
    <script type="text/javascript">




    function   PackSizeDelete(id) {

            swal({
                title: "Are you sure?",
                text: "",
                type: "success",
                showCancelButton: true,
                cancelButtonClass: 'btn-secondary waves-effect',
                confirmButtonClass: 'btn-success waves-effect waves-light',
                confirmButtonText: 'Yes!',
                closeOnConfirm: false
            }, function () {
                $('.confirm').prop("disabled", true);
                $('.cancel').prop("disabled", true);
                DeletePackSizeFianl(id);

            });



    }
    function DeletePackSizeFianl(id) {



        var urlpath = '@Url.Action("DeletePackSize", "ProductPackSize")';

        $.ajax({
            contentType: "application/json; charset=utf-8",
            data: { id: id },
            dataType: 'json',
            url: urlpath,
            type: "GET"
        })
            .success(function (result) {

                if (result.isSuccess) {

                    $('.confirm').prop("disabled", false);
                    $('.cancel').prop("disabled", false);
                    //swal.close();

                    swal("Data Delete Successfull");
                    window.location.href = '@Url.Action("ProductPackSizeList", "ProductPackSize")';


                }
            });
    }
    </script>
}
