IGFoodProject/Controllers/SalesRepresentativeController.cs
using IGFoodProject.DAL;
using IGFoodProject.Models;
using IGFoodProject.Utility;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IGFoodProject.ViewModel;
using Newtonsoft.Json;

namespace IGFoodProject.Controllers
{
    public class SalesRepresentativeController : Controller
    {
       private SalesRepresentativeDAL salesRepresentativeDAL = new SalesRepresentativeDAL();
        // GET: SalesRepresentative
        public ActionResult CreateSalesRepresentative(int srId = 0)
        {


            if (Session[SessionCollection.LoginUserEmpId] != null)
            {
                SRInfoMaster sRInfoMaster = salesRepresentativeDAL.GetSRDataForEdit(srId);
                return View(sRInfoMaster);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }
        public ActionResult GetDealerLogListForSR(int srId = 0)
        {
            SRInfoMaster sRInfoMaster = salesRepresentativeDAL.GetSRDataForEdit(srId,true);
            return PartialView("_DealerListForSRLog", sRInfoMaster);
        }

        public ActionResult SaveOrUpdateSRInfo(SRInfoMaster sRInfo)
        {
            ResultResponse result = new ResultResponse();
            result = salesRepresentativeDAL.SaveOrUpdateSrInformation(sRInfo);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SalesRepresentativeList()
        {

            if (Session[SessionCollection.LoginUserEmpId] != null)
            {

                List<SRInfoMaster> sRInfoMasterList = salesRepresentativeDAL.GetSRList();

                return View(sRInfoMasterList);
            }
            else
            {

                return RedirectToAction("Login", "Home");
            }
           
        }

        public ActionResult SrSalaryProcessEntry()
        {

            if (Session[SessionCollection.LoginUserEmpId] != null)
            {

                List<SRInfoMaster> sRInfoMasterList = salesRepresentativeDAL.GetSRList();

                return View(sRInfoMasterList);
            }
            else
            {

                return RedirectToAction("Login", "Home");
            }

        }

        public ActionResult GetAllOrdersOfDealers(DateTime? fromDate, DateTime? toDate)
        {
            DataTable dt = salesRepresentativeDAL.GetAllOrdersOfDealers(fromDate,toDate);

            return PartialView("_OrderDeliveryPendingReport", dt);
        }
        
        public dynamic SrSalaryProcess(ViewSRSalaryProcess viewSRSalaryProcess)
        {

            ResultResponse result = new ResultResponse();
            DataTable dt=new DataTable();
            viewSRSalaryProcess.EmpId = Convert.ToInt32(Session[SessionCollection.LoginUserEmpId]);
            dt = salesRepresentativeDAL.SaveSrSalaryProcessData(viewSRSalaryProcess);
           string JSONString = JsonConvert.SerializeObject(dt);
            return Json(JSONString, JsonRequestBehavior.AllowGet);
        }

        public ActionResult testData()
        {
            return View();
        }

        public ActionResult SrSalaryPaySlip()
        {

            if (Session[SessionCollection.LoginUserEmpId] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }

        }
        public ActionResult GetSRByCustomerId(int customerid)
        {
            List<SRInfoMaster> aList = salesRepresentativeDAL.GetSRByCustomerId(customerid);
            return Json(aList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSR(int customerid, DateTime fromDate, DateTime toDate)
        {
            List<SRInfoMaster> aList = salesRepresentativeDAL.GetSRList(customerid, fromDate, toDate);
            return Json(aList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCustomer(int typeid, DateTime fromDate, DateTime toDate)
        {
            List<ViewCustomerInfo> aList = salesRepresentativeDAL.GetCustomerList(typeid, fromDate, toDate);
            return Json(aList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DealerRetentionProcessEntry()
        {

            if (Session[SessionCollection.LoginUserEmpId] != null)
            {

                List<SRInfoMaster> sRInfoMasterList = salesRepresentativeDAL.GetSRList();

                return View();
            }
            else
            {

                return RedirectToAction("Login", "Home");
            }

        }
        public ActionResult GetAllOrdersOfDealersForRetention(DateTime? fromDate, DateTime? toDate)
        {
            DataTable dt = salesRepresentativeDAL.GetAllOrdersOfDealersForRetention(fromDate, toDate);
            string JSONString = JsonConvert.SerializeObject(dt);
            //return PartialView("_OrderDeliveryPendingReport", dt);
            return Json(JSONString, JsonRequestBehavior.AllowGet);
        }
        public dynamic SaveDealerRetentionProcess(DealerRetentionModel viewSRSalaryProcess)
        {

            ResultResponse result = new ResultResponse();
            DataTable dt = new DataTable();
            viewSRSalaryProcess.EmpId = Convert.ToInt32(Session[SessionCollection.LoginUserEmpId]);
            dt = salesRepresentativeDAL.SaveDealerRetentionProcessData(viewSRSalaryProcess);
            string JSONString = JsonConvert.SerializeObject(dt);
            return Json(JSONString, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DealerRetentionReport()
        {
            return View();
        }

        public ActionResult GetDealerRetentionSummary(DateTime fromDate, DateTime toDate, int customer)
        {           
            DataTable aObj = salesRepresentativeDAL.GetCustomerRetentionSummary(fromDate, toDate,  customer);
            string JSONresult;
            JSONresult = JsonConvert.SerializeObject(aObj);           
            return Json(JSONresult, JsonRequestBehavior.AllowGet);

        }

        public ActionResult DealerDamageProcessEntry()
        {

            if (Session[SessionCollection.LoginUserEmpId] != null)
            {

                List<SRInfoMaster> sRInfoMasterList = salesRepresentativeDAL.GetSRList();

                return View();
            }
            else
            {

                return RedirectToAction("Login", "Home");
            }

        }
        public ActionResult GetAllOrdersOfDealersForDamage(DateTime? fromDate, DateTime? toDate)
        {
            DataTable dt = salesRepresentativeDAL.GetAllOrdersOfDealersForDamage(fromDate, toDate);
            string JSONString = JsonConvert.SerializeObject(dt);
            //return PartialView("_OrderDeliveryPendingReport", dt);
            return Json(JSONString, JsonRequestBehavior.AllowGet);
        }
        public dynamic SaveDealerDamageProcess(DealerRetentionModel viewSRSalaryProcess)
        {

            ResultResponse result = new ResultResponse();
            DataTable dt = new DataTable();
            viewSRSalaryProcess.EmpId = Convert.ToInt32(Session[SessionCollection.LoginUserEmpId]);
            dt = salesRepresentativeDAL.SaveDealerDamageProcessData(viewSRSalaryProcess);
            string JSONString = JsonConvert.SerializeObject(dt);
            return Json(JSONString, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DealerDamageReport()
        {
            return View();
        }
        public ActionResult GetDealerDamageSummary(DateTime fromDate, DateTime toDate, int customer)
        {

            DataTable aObj = salesRepresentativeDAL.GetCustomerDamageSummary(fromDate, toDate, customer);
            string JSONresult;
            JSONresult = JsonConvert.SerializeObject(aObj);


            return Json(JSONresult, JsonRequestBehavior.AllowGet);

        }



        public ActionResult ListApproveSrSalary()
        {

            if (Session[SessionCollection.LoginUserEmpId] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }

        }
        public ActionResult DataforListApproveSrSalary(int monthId, int yearId)
        {

            List<SrSalaryApproval> aList = salesRepresentativeDAL.DataforListApproveSrSalary(monthId,yearId);
        

            return Json(aList, JsonRequestBehavior.AllowGet);

        }


        public ActionResult ApproveSrSalary(List<SrSalaryApproval> entity)
        {
            try
            {
                ResultResponse aResponse = new ResultResponse();
                string entryBy = Session[SessionCollection.UserName].ToString();
                foreach (var item in entity)
                {
                     aResponse = salesRepresentativeDAL.ApproveSrSalary(item, entryBy);
                }


              
                return Json(aResponse, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


        public ActionResult ListApproveDamage()
        {

            if (Session[SessionCollection.LoginUserEmpId] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }

        }
        public ActionResult DataforListApproveDamage(int monthId, int yearId)
        {


IGFoodProject/Views/SalesRepresentative/DealerDamageProcessEntry.cshtml

@{
    ViewBag.Title = "DealerRetentionProcessEntry";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h2>Dealer Damage Process</h2>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3 col-xs-5">
                                <label for="startDate">Damage Month</label>
                                <input type="text" id="startDate" autocomplete="off" class="form-control  datepicker " data-date-autoclose="true" data-date-today-highlight="true" data-date-format="dd-M-yyyy">
                            </div>

                            <div class="col-md-3 col-xs-3">
                                <button class="btn btn-block btn-info" style="margin-top: 18px" onclick="ShowReport()">Process</button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="" id="pendingConfirmationPartial">
        </div>

        <div id="ajaxLoaderDiv" style="position: fixed; top: 40%; left: 45%; z-index: 1234;">
            <img src="@Url.Content("~/AssetStatic/Images/Double Ring.gif")" alt="Loading..." class="ajax-loader" />
        </div>

    </div>
</section>

@section scripts{

    <script type="text/javascript">
        var monthsAll = [
            "January", "February", "March",
            "April", "May", "June",
            "July", "August", "September",
            "October", "November", "December"
        ];
        var firstDayFormated ;
        var lastDayFormated;

        $(function () {
            $('#ajaxLoaderDiv').hide();

            $('#startDate').datepicker({
                format: "MM-yyyy",
                viewMode: "months",
                minViewMode: "months",
                autoclose: true

            });

        });



        function ShowReport() {
            debugger;
            var monthPicker = $('#startDate').val();
            var indexofMon = monthPicker.indexOf('-');


            var month = monthPicker.substring(0, indexofMon).trim();
            var year = monthPicker.substring(indexofMon + 1, monthPicker.length).trim();
            var monthNumber = monthsAll.indexOf(month);


            var firstDay = new Date(year, monthNumber, 1);
            var lastDay = new Date(year, monthNumber + 1, 0);


            firstDayFormated = $.datepicker.formatDate("d-M-yy", new Date(firstDay));
            lastDayFormated = $.datepicker.formatDate("d-M-yy", new Date(lastDay));

                urlpath = '@Url.Action("GetAllOrdersOfDealersForDamage", "SalesRepresentative")';
                $.ajax({
                    url: urlpath,
                    data: { fromDate: firstDayFormated, toDate: lastDayFormated },
                    type: "Get",
                    dataType: 'json',
                    beforeSend: function () {
                        $('#ajaxLoaderDiv').show();
                    },
                    success: function (data) {
                        debugger;
                        var json = $.parseJSON(data);
                        var convalue=0;
                        for (var i = 0; i < json.length; i++) {
                            if (json[i].IsDeliveryConfirm == 0) {
                                convalue++;
                            }
                        }

                        if (convalue > 0) {


                            var html = "<div class='row'>";
                            html += "<div class='col-md-12'>";
                            html += "<div class='card card-primary'>";
                            html += "<div class='card-header'>";

                            html += "<button type='button' class='btn btn-danger' onclick='ModalPopUp()'>";
                            html += convalue + " delivery confirmation are pending";
                            html += "</button>";


                            html += "</div>";

                            html += "</div>";


                            html += "<div class='modal' id='myModal' role='dialog'>";
                            html += "<div class='modal-dialog modal-sm' style='max-width: 80% !important'>";
                            html += "<div class='modal-content'>";
                            html += "<div class='modal-header'>";
                            html += "<h4 style='text-align: center; font-weight: bold; padding-bottom: 0px; margin-top: 1px'>Pending Order List</h4>";
                            html += " </div>";
                            html += " <div class='modal-body' >";
                            html += " <table  border='1' class='table dataTable table-bordered table-striped table-hover'>";
                            html += " <thead>";
                            html += " <tr style='background-color: aliceblue'>";
                            html += " <th style='text-align: center'> SL NO</th>";
                            html += " <th style='text-align: center'> Sales Order No </th>";
                            html += " <th style='text-align: center'>Customer Name</th>";
                            html += " <th style='text-align: center'>Order Date</th>";
                            html += "  <th style='text-align: center'>Challan No</th>";
                            html += "  <th style='text-align: center'>Challan Date</th>";
                            html += "  <th style='text-align: center'>Due Amount</th>";
                            html += "  </tr>";

                            html += "  </thead>";

                            html += "   <tbody class='Traylist'>";
                            var count = 1;
                            for (var i = 0; i < json.length; i++) {
                                if (json[i].IsDeliveryConfirm == 0) {
                                    html += " <tr>";
                                    html += "  <td>" + count + "</td>";
                                    html += "  <td style='text-align: center'>" + json[i].SalesOrderNo + "</td>";
                                    html += "  <td style='text-align: center'>" + json[i].CustomerName + "</td>";
                                    html += "  <td style='text-align: center'>" + json[i].OrderDate + "</td>";
                                    html += "  <td style='text-align: center'>" + json[i].SalesOrderChallanNo + "</td>";
                                    html += "  <td style='text-align: center'>" + json[i].ChallanDate + "</td>";
                                    html += "  <td style='text-align: center'>" + json[i].totaldue + "</td>";
                                    html += "  </tr>";
                                    count++;

                                }
                            }

                            html += " </tbody>";


                            html += "</table>";

                            html += " </div>";
                            html += "<div class='modal-footer'>";

                            html += "   <button type='button' class='btn btn-danger' id='clsButton' data-dismiss='modal'>Close</button>";
                            html += " </div>";
                            html += " </div>";
                            html += " </div>";
                            html += "</div>";


                            html += "</div>";

                            html += "</div>";

                            $("#pendingConfirmationPartial").html(html);

                        } else {
                            var html = "<div class='row'>";
                            html += "<div class='col-md-12'>";
                            html += "<div class='card card-primary'>";
                            html += "<div class='card-header'>";

                            html += "<p> No Orders' delivery confirmation pending </p>";
                           
                            html += "</div>";

                            html += "</div>";
                            html += "</div>";

                            html += "</div>";

                            $("#pendingConfirmationPartial").html(html);
                            processSrSalary();
                        }

                    },

                    complete: function () {

                        $('#dealerSrTable').rowspanizer({
                            vertical_align: 'middle',
                            columns: [0]
                        });
                        $('#ajaxLoaderDiv').hide();
                    }
                });

        }
        function ModalPopUp() {
            $("#myModal").modal();
        }

        function processSrSalary() {
            if (Validation()) {
                swal({
                    title: "Are you sure?",
                    text: "",
                    type: "success",
                    showCancelButton: true,
                    cancelButtonClass: 'btn-secondary waves-effect',
                    confirmButtonClass: 'btn-success waves-effect waves-light',
                    confirmButtonText: 'Yes!',
                    closeOnConfirm: false
                },
                    function () {
                        $('.confirm').prop("disabled", true);
                        $('.cancel').prop("disabled", true);
                        processSrSalaryFinal();
                    });
            }
        }
        function processSrSalaryFinal() {
            debugger;

            var SRSalaryProcess = {};
            SRSalaryProcess["FromDate"] = firstDayFormated;
            SRSalaryProcess["ToDate"] = lastDayFormated;
            debugger;
             var urlpath = '@Url.Action("SaveDealerDamageProcess", "SalesRepresentative")';
                $.ajax({
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify(SRSalaryProcess) ,
                    dataType: 'json',
                    url: urlpath,
                    type: "POST",
                    success: function (result) {
                        //alert(result.StatusId);
                        var json = $.parseJSON(result);
                        //alert(json[0].StatusId);


                        //json.users[3].name
                        debugger;
                        if (json[0].StatusId == 2) {
                           // $('.confirm').prop("disabled", false);
                           // $('.cancel').prop("disabled", false);
                            swal({
                                title: 'Dealer Damage Process Successfull',
                                type: 'success',
                                closeOnCancel: true
                            });
                            @*function() {
                                window.location.href = '@Url.Action("SrSalaryPaySlip", "SalesRepresentative")';
                            });*@
                        } else if (json[0].StatusId == 1) {
                            ShowMessage('Already dealer Damage adjust from  sales collection');
                        } else {
                            ShowMessage('Please Give Data Correctly!!');
                        }
                    },
                    error: function () {
                        ShowMessage('Please Give Data Correctly!!');
                    }
                });

        }

        function Validation() {
            var isValid = true;

            if ($('startDate').val() == "") {
                isValid = false;
                message = ("Please select month");
            }
            if (isValid == false) {
                ShowMessage(message);
            }
            return isValid;
        }
    </script>

}


IGFoodProject/Views/SalesRepresentative/SalesRepresentativeList.cshtml

@{
    ViewBag.Title = "SalesRepresentativeList";
}

@using IGFoodProject.Models
@model IEnumerable<SRInfoMaster>
@{ int count = 1;}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h2>Sales Representative List</h2>
                        @Html.ActionLink("Create Sales Representative", "CreateSalesRepresentative", "SalesRepresentative", new { @class = "btn btn-success btn-sm float-right" })
                    </div>
                    <div class="card-body">
                        @if (Model.Any())
                        {

                            <table id="srTable" border="1" class="table dataTable table-bordered table-striped table-hover">
                                <thead>
                                    <tr style="background-color: aliceblue">

                                        <th style="text-align: center">SL</th>
                                        <th style="text-align: center">SR Name</th>
                                        <th style="text-align: center">SR Mobile No</th>
                                        <th style="text-align: center">SR Email</th>
                                        <th style="text-align: center">SR Address</th>
                                        <th style="text-align: center">Action</th>
                                    </tr>

                                </thead>

                                <tbody class="Traylist">
                                    @foreach (var row in Model)
                                    {
                                        <tr class="rowTr" id="@row.SrId">

                                            <td>@count</td>
                                            <td style="text-align: center">@row.SrName</td>
                                            <td style="text-align: center">@row.SrMobileNumber</td>
                                            <td style="text-align: center">@row.SrEmail</td>
                                            <td style="text-align: center">@row.SrAddress</td>


                                            <td style="text-align: center">
                                                @Html.ActionLink("Edit SR", "CreateSalesRepresentative", "SalesRepresentative", new { srId = row.SrId }, new { @class = "btn btn-info btn-sm" })
                                                <button class="btn btn-sm btn-success" id="srDealerLog" onclick="SrDealerLog(@row.SrId);">See Details</button>

                                            </td>

                                        </tr>
                                        count++;
                                    }
                                </tbody>


                            </table>
                        }
                        else
                        {
                            <p>NO DATA FOUND</p>

                        }

                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal" id="logModal">
    <div class="modal-dialog modal-sm" style="max-width: 80% !important">
        <div class="modal-content">
            <div class="modal-header">
                <h4 style="text-align: center; font-weight: bold; padding-bottom: 0px; margin-top: 1px">SR-Delaer List</h4>
            </div>
            <div class="modal-body" id="logList">


            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-danger" id="clsButton" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script type="text/javascript">

        function SrDealerLog(srId) {
            debugger;


                urlpath = '@Url.Action("GetDealerLogListForSR", "SalesRepresentative")';
                $.ajax({
                    url: urlpath,
                    data: { srId:srId },
                    type: "Get",
                    success: function (data) {
                        debugger;
                        $("#logList").html(data);
                    },
                    complete: function () {
                        $("#logModal").modal('show');
                    }
                });

        }

        function popup() {
            $("#logModal").modal('show');
        }
    </script>
}

IGFoodProject/Views/SalesRepresentative/_DealerListForSRLog.cshtml
@using IGFoodProject.Models
@model SRInfoMaster
@{ int count = 1;}
<div class="row">
    <div class="col-md-3" id="divSrName">
        <div class="form-group">
            <label for="srName">SR Name *</label>
            <input type="text" class="form-control" disabled id="srName" value="@Model.SrName">

        </div>
    </div>
    <div class="col-md-3" id="divSrMobileNumber">
        <div class="form-group">
            <label for="srMobileNumber">SR Mobile Number *</label>
            <input type="text" class="form-control" disabled id="srMobileNumber" value="@Model.SrMobileNumber">

        </div>
    </div>
    <div class="col-md-3" id="divSrEmail">
        <div class="form-group">
            <label for="srEmail">SR Email</label>
            <input type="text" class="form-control" disabled id="srEmail" value="@Model.SrEmail">

        </div>
    </div>
    <div class="col-md-3" id="divSrAddress">
        <div class="form-group">
            <label for="srAddress">SR Address</label>
            <input type="text" class="form-control" disabled id="srAddress" value="@Model.SrAddress">

        </div>
    </div>

    <input type="text" class="form-control" id="srId" value="@Model.SrId" style="display: none">

</div>

<table id="" border="1" class="table dataTable table-bordered table-striped table-hover">
    <thead>
        <tr style="background-color: aliceblue">
            <th style="text-align: center"> SL NO</th>
            <th style="text-align: center">Code</th>
            <th style="text-align: center">Customer Name</th>
            <th style="text-align: center">Phone</th>
            <th style="text-align: center">Status</th>
            <th style="text-align: center">Active Date</th>
            <th style="text-align: center">Inactive Date</th>
        </tr>

    </thead>

    <tbody class="Traylist">
        @foreach (var item in Model.SRDealerDetailsList)
        {
            <tr>
                <td>@count</td>
                <td style="text-align: center">@item.CustomerInformation.CustomerCode</td>
                <td style="text-align: center">@item.CustomerInformation.CustomerName</td>
                <td style="text-align: center">@item.CustomerInformation.Phone</td>
                <td style="text-align: center">@item.ActiveStatus</td>
                <td style="text-align: center">@item.ActiveDate</td>
                <td style="text-align: center">@item.DeactiveDate</td>
            </tr>
            count++;
        }
    </tbody>


</table>


IGFoodProject/Views/SalesRepresentative/testData.cshtml

@{
    ViewBag.Title = "testData";
}

<h2>testData</h2>

<button type="button" class="btn btn-info" data-toggle="modal" data-target="#modal1">
    Launch Info Modal
</button>
<div class="modal modal-primary" id="modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Primary Modal</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-outline">Save changes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>