IGFoodProject/Controllers/ExchangeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IGFoodProject.DAL;
using IGFoodProject.Models;
using IGFoodProject.Utility;

namespace IGFoodProject.Controllers
{
    public class ExchangeController : Controller
    {
        ExchangeDAL aDal = new ExchangeDAL();
        // GET: Exchange
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ExchangeList() 
        {
            string empId = Session[SessionCollection.LoginUserEmpId].ToString();
            List<ItemExchange> aList = aDal.ExchangeList(empId);
            return View(aList);
        }

        public ActionResult ExchangeApprove()
        {
            List<ItemExchange> aList = aDal.ExchangeApproveList(); 
            return View(aList);
        }
        
        public JsonResult LoadItemGroup()
        {
            List<ItemExchange> alist = aDal.LoadItemGroup();
            return Json(alist, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadItem( int groupId)
        {
            List<ItemExchange> alist = aDal.LoadItem(groupId);
            return Json(alist, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadProductroup()
        {
            List<ItemExchange> alist = aDal.LoadProductroup(); 
            return Json(alist, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadProduct(int groupId) 
        {
            List<ItemExchange> alist = aDal.LoadProduct(groupId);
            return Json(alist, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadStockQty(int warehouseId, int groupId, int itemId) 
        {
            ItemExchange exchange = aDal.LoadStockQty(warehouseId,groupId, itemId); 
            return Json(exchange, JsonRequestBehavior.AllowGet); 
        }

        public ActionResult SaveExchangeRequisition(ItemExchange aMaster)  
        {
            aMaster.CreateBy = Session[SessionCollection.UserName].ToString();
            ResultResponse aResponse = aDal.SaveExchangeRequisition(aMaster); 
            return Json(aResponse, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveAccept(decimal appQty, int exchangeId)
        {
            string empId = Session[SessionCollection.UserName].ToString();
            ResultResponse aResponse = aDal.SaveAccept(appQty, exchangeId, empId);
            return Json(aResponse, JsonRequestBehavior.AllowGet);
        }


    }
}

IGFoodProject/Views/Exchange/ExchangeApprove.cshtml
@model IEnumerable<IGFoodProject.Models.ItemExchange>
@{
    ViewBag.Title = "ExchangeApprove";
}





<section class="content">


    <div class="row">

        <div class="col-xs-12">
            <div class="box box-success">

                <div class="box-header">
                    <h4 class="box-title">RM To FG Exchange Approve</h4>

                </div>
                <br />
                <!-- /.box-header -->
                <div class="box-body table-responsive">
                    <table id="mytable1" class="table table-bordered table-striped">
                        <thead style="background-color:  #ccffdc">
                            <tr>
                                <th style="text-align: center" rowspan="2">SL</th>
                                <th style="text-align: center" colspan="4">RM</th>
                                <th style="text-align: center" colspan="4">FG</th>
                                <th style="text-align: center" rowspan="2">Exchange Qty</th>
                                <th style="text-align: center" rowspan="2">Approved Qty</th>
                                <th style="text-align: center" rowspan="2">Stock Qty</th>
                                <th style="text-align: center" rowspan="2">Exchange Date</th>
                                <th style="text-align: center" rowspan="2">Remarks</th>
                                <th style="text-align: center" rowspan="2">Create By</th>
                                <th style="text-align: center" rowspan="2">Create Date</th>
                                <th style="text-align: center" rowspan="2">Action</th>
                            </tr>
                            <tr>
                                <th style="text-align: center">Location </th>
                                <th style="text-align: center">Warehouse</th>
                                <th style="text-align: center">Group</th>
                                <th style="text-align: center">Item</th>

                                <th style="text-align: center">Location </th>
                                <th style="text-align: center">Warehouse</th>
                                <th style="text-align: center">Group</th>
                                <th style="text-align: center">Product</th>
                            </tr>
                        </thead>
                        <tbody id="manuallist">
                            @{
                                var count = 1;
                            }
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td style="text-align: center" class="ExportLabelTD">@count</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.RmLocationName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.RmWarehouseName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.RmItemGroupName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.RmItemName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.FgLocationName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.FgWarehouseName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.FgProductGroupName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.FgProductName</td>
                                    <td style="text-align: center" class="ExportLabelTD" id="txtExchangeQty_@item.ExchangeId">@item.ExchangeQty</td>

                                    <td style="text-align: center" class="ExportLabelTD"><input type="number" style="width: 80px;" id="txtAccept_@item.ExchangeId" oninput="checkQty(@item.ExchangeId)" value="@item.ExchangeQty" /></td>

                                    <td style="text-align: center" class="ExportLabelTD" id="stockInQty_@item.ExchangeId">@item.StockQty</td>

                                    <td style="text-align: center" class="ExportLabelTD">@item.ExeDate</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.Remarks</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.CreateBy</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.CreateDate</td>
                                    <td style="text-align: center" class="ExportLabelTD"><button class="btn btn-sm btn-success" onclick="Accept(@item.ExchangeId)">Approve</button></td>

                                </tr>
                                count++;
                            }

                        </tbody>
                    </table>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>





    </div>



</section>



@section Scripts
{
    <script>
        function GenerateNew() {
            window.location.href = '@Url.Action("Index", "Exchange")';
        }

        function checkQty(exchangeId) {
            debugger;
            var appQty = parseFloat($('#txtAccept_' + exchangeId).val());
            var stock = parseFloat($('#stockInQty_' + exchangeId).html());
            var exchange = parseFloat($('#txtExchangeQty_' + exchangeId).html());

            if (appQty > stock) {
                swal("Stock is not available.");
                $('#txtAccept_' + exchangeId).val(exchange);
                return;
            }
            if (appQty > exchange) {
                swal("Please check exchange quantity.");
                $('#txtAccept_' + exchangeId).val(exchange);
                return;
            }


        }

        function Accept(exchangeId) {

            if ($('#txtAccept_' + exchangeId).val() == 0 || $('#txtAccept_' + exchangeId).val() == '') {
                swal("Please input Approved Qty");
                return;
            } else {

                swal({
                    title: "Are you sure?",
                    text: "",
                    type: "success",
                    showCancelButton: true,
                    cancelButtonClass: 'btn-secondary waves-effect',
                    confirmButtonClass: 'btn-success waves-effect waves-light',
                    confirmButtonText: 'Yes!',
                    closeOnConfirm: false

                }, function () {
                    $('.confirm').prop("disabled", true);
                    $('.cancel').prop("disabled", true);
                    SaveAccept(exchangeId);

                });
            }
        }


        function SaveAccept(exchangeId) {
            debugger;
            var appQty = parseFloat($('#txtAccept_' + exchangeId).val());


            var urlpath = '@Url.Action("SaveAccept", "Exchange")'; 

            $.ajax({
                contentType: "application/json",
                data: { appQty: appQty, exchangeId: exchangeId },
                dataType: 'json',
                url: urlpath,
                type: "Get"
            })
                .success(function (result) {

                    if (result.isSuccess == true) {

                        swal({
                            title: 'Approved Successfully',
                            type: 'success',
                            closeOnCancel: true

                        },
                            function () {
                                window.location.href = '@Url.Action("ExchangeApprove", "Exchange")';
                            });
                    }
                });
        }


    </script>
}

IGFoodProject/Views/Exchange/ExchangeList.cshtml
@{
    ViewBag.Title = "ExchangeList";
}

@model IEnumerable<IGFoodProject.Models.ItemExchange>
@{
    ViewBag.Title = "ExchangeList";
}





<section class="content">


    <div class="row">

        <div class="col-xs-12">
            <div class="box box-success">

                <div class="box-header">
                    <h4 class="box-title">RM To FG Exchange List</h4>
                    
                </div>
                <br/>
                <!-- /.box-header -->
                <div class="box-body table-responsive">
                    <table id="mytable1" class="table table-bordered table-striped">
                        <thead style="background-color:  #ccffdc">
                            <tr>
                                <th style="text-align: center" rowspan="2">SL</th>
                                <th style="text-align: center" colspan="4">RM</th>
                                <th style="text-align: center" colspan="4">FG</th>
                                <th style="text-align: center" rowspan="2">Exchange Qty</th>
                                <th style="text-align: center" rowspan="2">Approved Qty</th>
                                <th style="text-align: center" rowspan="2">Exchange Date</th>
                                <th style="text-align: center" rowspan="2">Remarks</th>
                                <th style="text-align: center" rowspan="2">Create By</th>
                                <th style="text-align: center" rowspan="2">Create Date</th>
                                <th style="text-align: center" rowspan="2">Approved By</th>
                                <th style="text-align: center" rowspan="2">Approved Date</th>
                                <th style="text-align: center" rowspan="2">Status</th>
                            </tr>
                            <tr>
                                <th style="text-align: center">Location </th>
                                <th style="text-align: center">Warehouse</th>
                                <th style="text-align: center">Group</th>
                                <th style="text-align: center">Item</th>

                                <th style="text-align: center">Location </th>
                                <th style="text-align: center">Warehouse</th>
                                <th style="text-align: center">Group</th>
                                <th style="text-align: center">Product</th>
                            </tr>
                        </thead>
                        <tbody id="manuallist">
                            @{
                                var count = 1;
                            }
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td style="text-align: center" class="ExportLabelTD">@count</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.RmLocationName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.RmWarehouseName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.RmItemGroupName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.RmItemName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.FgLocationName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.FgWarehouseName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.FgProductGroupName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.FgProductName</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.ExchangeQty</td>
                                    @if (item.ApprovedQty > 0)
                                    {
                                        <td style="text-align: center" class="ExportLabelTD">@item.ApprovedQty</td>
                                    }
                                    else
                                    {
                                        <td style="text-align: center" class="ExportLabelTD"></td>
                                    }
                                    <td style="text-align: center" class="ExportLabelTD">@item.ExeDate</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.Remarks</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.CreateBy</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.CreateDate</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.ApprovedBy</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.ApprovedDate</td>
                                    <td style="text-align: center" class="ExportLabelTD">@item.ApprovedStatus</td>

                                </tr>
                                count++;
                            }
                            
                        </tbody>
                    </table>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>





    </div>



</section>



@section Scripts
{
    <script>
        function GenerateNew() {
            window.location.href = '@Url.Action("Index", "Exchange")';
        }

       

    </script>
}